#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FireTVApp.Resource", IsApplication=true)]

namespace FireTVApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int a1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int b = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int b1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int c = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int c1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int d = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int d1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int e = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int e1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int f = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int f1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int g = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int g1 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int h = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int h1 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int i = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int i1 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int j = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int j1 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int k = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int k1 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int l = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int l1 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int m = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int m1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int n = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int n1 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int o = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int o1 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int p = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int p1 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int q = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int q1 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int r = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int r1 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int s = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int s1 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int t = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int t1 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int v = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int v1 = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int DetailImageView = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Grid = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Title = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int title = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
